#!/bin/sh

./build/cholupdate lp_qap15 > Outputs/CholUpdate/lp_qap15_chol.out # time-consuming
./build/cholupdate lp_sierra > Outputs/CholUpdate/lp_sierra_chol.out
./build/cholupdate lp_scsd8 > Outputs/CholUpdate/lp_scsd8_chol.out
./build/cholupdate lp_pds_02 > Outputs/CholUpdate/lp_pds_02_chol.out
./build/cholupdate lp_share1b > Outputs/CholUpdate/lp_share1b_chol.out
./build/cholupdate lp_qap12 > Outputs/CholUpdate/lp_qap12_chol.out
./build/cholupdate lp_ship04s > Outputs/CholUpdate/lp_ship04s_chol.out
./build/cholupdate lp_stocfor3 > Outputs/CholUpdate/lp_stocfor3_chol.out
./build/cholupdate lp_ken_18 > Outputs/CholUpdate/lp_ken_18_chol.out # > 270hrs
./build/cholupdate lp_cre_a > Outputs/CholUpdate/lp_cre_a_chol.out
